# Generated by Django 5.2.4 on 2025-12-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_rename_customer_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="product/default.png", upload_to="product/"
            ),
        ),
    ]
